//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibCheck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibCheck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Greetings,&lt;/p&gt;
        ///    &lt;p&gt;
        ///        Thank you for registering to LibCheck Book Borrowing and Returning System in &lt;b&gt;%school%.&lt;/b&gt;
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        Your registered email address will receive notification regarding the book transactions 
        ///        (like book borrowing and returning, incoming and past dues, etc.) to keep you up to date.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;Student ID: &lt;b&gt;%stID%&lt;/b&gt;&lt;/p&gt;
        ///    &lt;p&gt;Name: &lt;b&gt;%name%&lt;/b&gt;&lt;/p&gt;
        ///    
        ///    &lt;p&gt;Thank you once again and enjoy!&lt;/p&gt;
        ///        
        ///    &lt;p&gt;
        ///        &lt;u&gt;%libr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddEmailTxt {
            get {
                return ResourceManager.GetString("AddEmailTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audio_24px {
            get {
                object obj = ResourceManager.GetObject("audio_24px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back_card {
            get {
                object obj = ResourceManager.GetObject("back_card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back_to_50px {
            get {
                object obj = ResourceManager.GetObject("back_to_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Greetings,&lt;/p&gt;
        ///    &lt;p&gt;
        ///        We notify you because you borrowed a book. Here&apos;s the information:
        ///        &lt;br/&gt;
        ///    &lt;/p&gt;
        ///    &lt;p&gt;ISBN: &lt;b&gt;%isbn%&lt;/b&gt;&lt;/p&gt;
        ///    &lt;p&gt;Title: &lt;b&gt;%title%&lt;/b&gt;&lt;/p&gt;
        ///    &lt;p&gt;Author: &lt;b&gt;%author%&lt;/b&gt;&lt;/p&gt;
        ///
        ///    &lt;p&gt;
        ///        Please return the book on or before &lt;b&gt;%due%&lt;/b&gt; to prevent overdue cost. Thank you!
        ///    &lt;/p&gt;
        ///        
        ///    &lt;p&gt;
        ///        &lt;u&gt;%librarian%&lt;/u&gt;&lt;br/&gt;
        ///        Librarian in &lt;b&gt;%school%.&lt;/b&gt;
        ///    &lt;/p&gt;
        ///        
        ///&lt;p style=&quot;text-align: center&quot;&gt;(Do not reply to this ema [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BookBorrowedEmail {
            get {
                return ResourceManager.GetString("BookBorrowedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel_24px {
            get {
                object obj = ResourceManager.GetObject("cancel_24px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;An email was sent from a librarian:&lt;/p&gt;
        ///
        ///&lt;blockquote&gt;
        ///%text%
        ///&lt;/blockquote&gt;      
        ///
        ///&lt;p&gt;
        ///    &lt;u&gt;%librarian%&lt;/u&gt;&lt;br/&gt;
        ///    Librarian in &lt;b&gt;%school%.&lt;/b&gt;
        ///&lt;/p&gt;
        ///        
        ///&lt;p style=&quot;text-align: center&quot;&gt;(Do not reply to this email address.)&lt;/p&gt;.
        /// </summary>
        internal static string CustomEmail {
            get {
                return ResourceManager.GetString("CustomEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap empty_trash_32px {
            get {
                object obj = ResourceManager.GetObject("empty_trash_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error_24px {
            get {
                object obj = ResourceManager.GetObject("error_24px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorDiag_Icon {
            get {
                object obj = ResourceManager.GetObject("ErrorDiag_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap front_card {
            get {
                object obj = ResourceManager.GetObject("front_card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hourglass_64px {
            get {
                object obj = ResourceManager.GetObject("hourglass_64px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_book_borrowed_45 {
            get {
                object obj = ResourceManager.GetObject("icons8-book-borrowed-45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_book_damage_45 {
            get {
                object obj = ResourceManager.GetObject("icons8-book-damage-45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_books_45 {
            get {
                object obj = ResourceManager.GetObject("icons8-books-45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_compose_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-compose-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_compose_40 {
            get {
                object obj = ResourceManager.GetObject("icons8-compose-40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_email_45 {
            get {
                object obj = ResourceManager.GetObject("icons8-email-45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_email_queue_45 {
            get {
                object obj = ResourceManager.GetObject("icons8-email-queue-45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_home_45 {
            get {
                object obj = ResourceManager.GetObject("icons8-home-45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_log_45 {
            get {
                object obj = ResourceManager.GetObject("icons8-log-45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_statistics_45 {
            get {
                object obj = ResourceManager.GetObject("icons8-statistics-45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_student_45 {
            get {
                object obj = ResourceManager.GetObject("icons8-student-45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_user_locked_64 {
            get {
                object obj = ResourceManager.GetObject("icons8-user-locked-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_users_45 {
            get {
                object obj = ResourceManager.GetObject("icons8-users-45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info_24px {
            get {
                object obj = ResourceManager.GetObject("info_24px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_64px {
            get {
                object obj = ResourceManager.GetObject("key_64px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Librarian_Settings {
            get {
                object obj = ResourceManager.GetObject("Librarian_Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LOGO_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("LOGO-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OngoingDueEmail {
            get {
                return ResourceManager.GetString("OngoingDueEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Portrait_Mode_Scanning_50px {
            get {
                object obj = ResourceManager.GetObject("Portrait Mode Scanning_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap radioactive_24px {
            get {
                object obj = ResourceManager.GetObject("radioactive_24px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_32px {
            get {
                object obj = ResourceManager.GetObject("refresh_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reg_ShowPass {
            get {
                object obj = ResourceManager.GetObject("Reg_ShowPass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_32px {
            get {
                object obj = ResourceManager.GetObject("save_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Greetings,&lt;/p&gt;
        ///    &lt;p&gt;
        ///        The librarian successfully updated an email address and from now on, 
        ///        the email address you notified to update, will received notification 
        ///        regarding the book transactions (like book borrowing and returning, incoming and past dues, etc.) 
        ///        to keep you up to date.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;Student ID: &lt;b&gt;%stID%&lt;/b&gt;&lt;/p&gt;
        ///    &lt;p&gt;Name: &lt;b&gt;%name%&lt;/b&gt;&lt;/p&gt;
        ///    
        ///    &lt;p&gt;Thank you and have a great day!&lt;/p&gt;
        ///        
        ///    &lt;p&gt;
        ///        &lt;u&gt;%librarian%&lt;/u&gt;&lt;br/&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateEmailTxt {
            get {
                return ResourceManager.GetString("UpdateEmailTxt", resourceCulture);
            }
        }
    }
}
